### PR TITLE
Functions with allocations

### PR DESCRIPTION
**Pull request by MCJOHN974**
Here I added functional solution, but with heap allocations like in ```objects.cpp```

### CODE REVIEW

**Comment by yegor256** [comment]
@MCJOHN974 why do you change `objects.cpp` in this PR? Is it necessary?

**Comment by MCJOHN974** [comment]
@yegor256 i remove changing of ```objects.cpp```

**Comment by yegor256** [comment]
@MCJOHN974 the build is not green here. Did you run `make` and `make sa` locally?

**Comment by MCJOHN974** [comment]
@yegor256 lint is green here

**Comment by yegor256** [comment]
@MCJOHN974 thanks!

**Pull request merged**
