### PR TITLE
Statck objects

### PR DESCRIPTION
**Pull request by MCJOHN974**
One more fibo implementation. OOP with inheritance, but without heap allocations and pure virtual classes. @yegor256

### CODE REVIEW

**Comment by MCJOHN974** [comment]
@yegor256 yes, sorry, I should create new branches more carefully later. But anyway I change ```objects.cpp``` in #19. In #18 I explained why

**Comment by yegor256** [comment]
@MCJOHN974 please, remove this change from this branch. We must keep branches isolated. Don't mix changes.

**Comment by MCJOHN974** [comment]
@yegor256 i fix changing of ```objects.cpp```

**Comment by yegor256** [comment]
@MCJOHN974 the build is not green on your branch. Did you try to run `make` and then `make sa` on your computer?

**Comment by MCJOHN974** [comment]
@yegor256 lint is green now

**Comment by yegor256** [comment]
@MCJOHN974 thanks!

**Pull request merged**
