### PR TITLE
Formula

### PR DESCRIPTION
**Pull request by MCJOHN974**
@yegor256 here added counting of fibonacci number using [Binet's formula](https://artofproblemsolving.com/wiki/index.php/Binet%27s_Formula) with ```O(log(n))``` time complexity (complexity of power calculating)

### CODE REVIEW

**Comment by yegor256** [comment]
@MCJOHN974 still broken...

**Comment by MCJOHN974** [comment]
@yegor256 ```make sa``` don't show any lint errors lokally

**Comment by MCJOHN974** [comment]
But now simple ```make``` shows an error

**Comment by MCJOHN974** [comment]
I remove my file and ```make``` still show same error. I tested my ```calc()``` with mine main and it works correctly

**Comment by yegor256** [comment]
@MCJOHN974 if the build is broken in the master branch before you start making changes, submit a ticket to the project and the project owner to fix the build. When the build is fixed, continue with making changes.

**Comment by MCJOHN974** [comment]
@yegor256 and here make is green too

**Comment by yegor256** [comment]
@MCJOHN974 thanks!

**Pull request merged**
