### PR TITLE
Statics

### PR DESCRIPTION
**Pull request by MCJOHN974**
Here was added implementations of fibonacci algorithm via static class member functions. @yegor256

### CODE REVIEW

**Comment by yegor256** [comment]
@MCJOHN974 you also change `objects.cpp` here. Is it a mistake?

**Comment by MCJOHN974** [comment]
@yegor256, i think i fix all issues with this pr

**Comment by yegor256** [comment]
@MCJOHN974 good idea, but the build is not green here :( can't merge

**Comment by MCJOHN974** [comment]
@yegor256, linter is red because of  ```interpreter.cpp```, as I understand

**Comment by MCJOHN974** [comment]
@yegor256 now I update repo locally and sa is ok in my machine

**Comment by yegor256** [comment]
@MCJOHN974 thanks!

**Pull request merged**
