### PR TITLE
Some Haskell

### PR DESCRIPTION
**Pull request by kostochkin**

### CODE REVIEW

**Comment by yegor256** [comment]
@kostochkin I think it would also be necessary to modify GitHub Action workflows, to make sure Haskell is installed in Ubuntu

**Comment by yegor256** [comment]
@kostochkin our GitHub Action build is broken, that's I'm not merging and waiting... We don't know how to install Clang 13 on Ubuntu. We have the 7th version by default. Maybe you can help?

**Comment by kostochkin** [comment]
@yegor256 I copied my Dockerfile contents to the github workflow file, but it failed with pip.
Installing llvm is described here: https://apt.llvm.org/

**Comment by yegor256** [comment]
@kostochkin see the build log: https://github.com/yegor256/fibonacci/runs/4957526630?check_suite_focus=true Clang 13 is being installed (it seems), but then `make env` says that `clang` is still in version 7.0

**Comment by kostochkin** [comment]
@yegor256 It seems working now, but the cpps don't pass SA check

**Comment by yegor256** [comment]
@kostochkin thanks a lot!

**Pull request merged**
